# docker-compose.yml
# Use this to configure networking for mac users

version: '3'


networks:
  analytics_network:
    driver: bridge

services:

  experiments:
    networks:
      - analytics_network
    ports:
      - "8888:8888"
